### ISSUE TITLE
`envoy-ingress` backend services unhealthy when installing Kubeflow on GKE version `1.17.9-gke.1504`

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/gcp-blueprints#160]
`envoy-ingress` backend services unhealthy when installing Kubeflow on GKE version `1.17.9-gke.1504`

originally reported in https://github.com/kubeflow/gcp-blueprints/pull/141

**Comment by Bobgy** [comment]
The PR proposed to

> Add the `cloud.google.com/neg: '{"ingress": false}'` annotation to `istio-ingressgateway` to disable **container-native load balancing** (neg) which is enabled by default for GKE clusters >= 1.17 ( https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#using )

However, we were not sure why we needed this.

**Comment by Bobgy** [comment]
I just verified the problem exists when I remove the `cloud.google.com/neg: '{"ingress": false}'` annotation. Therefore, we should figure out why and push the patch fix upstream to manifests repo.

**Comment by Bobgy** [comment]
I added the annotation back, but it doesn't immediately recover. I noticed `backend-updater-0` reconciles every hour...
So I deleted the pod to force a reconciliation, after that the backend service came back healthy.

**Comment by Bobgy** [comment]
In fact, I never reproduced the problem because of the annotation `cloud.google.com/neg: '{"ingress": false}'`, but rather that each time after I delete `istio-ingressgateway`, the backend services unhealthy error message shows up.

And after force rerunning `backend-updater-0` pod, the error goes away.

**Comment by parthmishra** [comment]
I'm wondering if I'm running into a similar issue as this. I tried deploying full KF 1.2 regional cluster (K8s version 	
1.17.14-gke.1600) to a VPC and `envoy-ingress` created NEG as the backend service. Then, the JWT audience isn't patched correctly because the names of NEG backend services isn't grepped as the `backend-updater` is expecting an instance-group backend. 

Here are logs showing this behavior:

```bash 
++ kubectl --namespace=istio-system get ingress envoy-ingress -o 'jsonpath={.metadata.annotations.ingress\.kubernetes\.io/backends}'
+ BACKENDS='{"k8s1-4cdd1290-istio-system-istio-ingressgateway-80-50723453":"HEALTHY"}'
+ echo 'fetching backends info with envoy-ingress: {"k8s1-4cdd1290-istio-system-istio-ingressgateway-80-50723453":"HEALTHY"}'
fetching backends info with envoy-ingress: {"k8s1-4cdd1290-istio-system-istio-ingressgateway-80-50723453":"HEALTHY"}
++ echo '{"k8s1-4cdd1290-istio-system-istio-ingressgateway-80-50723453":"HEALTHY"}'
++ grep -o 'k8s-be-31079--[0-9a-z]\+'
backend name is
+ BACKEND_NAME=
```

So restarting the `iap-enabler` and/or `backend-updater` pod won't fix the issue as it will never get the backend name. If I manually patch the JWT audience for `ingress-jwt` with the ID of the NEG backend and manually update the health-check path to `/healthz/ready`, then everything works. 

Also, I can't replicate this issue with zonal clusters if that's relevant. 

@Bobgy should the annotation on the Ingress be kept to disallow NEGs or is it unrelated?
