### ISSUE TITLE
Do we need following command in deployment steps?

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/gcp-blueprints#257]
kubectl config set-context --current --namespace ${KF_PROJECT}

**Comment by edi-bice-by** [comment]
I'm trying to deploy kubeflow 1.3 via gcp-blueprints and ran into the following which puzzled me as I wasn't expecting to see my GCP project as a namespace - maybe it is due to missing the step you listed above

edibice@MD1-1029014MBP kubeflow % make apply  
cluster_name_regex=^[a-z][-a-z0-9]{0,22}[a-z0-9]$
The kubeflow cluster name "kubeflow13" is valid.
PROJECT=blah-blah-blah NAME=kubeflow13 ./hack/check_domain_length.sh
Build directory: ./build
Component path: common/cnrm
Apply component resources: common/cnrm
Found Makefile, call 'make apply' of this component Makefile. 
echo ./build
./build
/Library/Developer/CommandLineTools/usr/bin/make apply-cnrm build_dir=./build
rm -rf ./build && mkdir -p ./build
kustomize build -o ./build ./
kubectl --context=kubeflow13-mgmt apply -f ./build
Error from server (NotFound): error when creating "build/compute.cnrm.cloud.google.com_v1beta1_computeaddress_kubeflow13-ip.yaml": namespaces "blah-blah-blah" not found

**Comment by zijianjoy** [comment]
Thanks @edi-bice-by! Would you like to check whether you have such namespace in management cluster context?

```
kubectl get namespace --context=kubeflow13-mgmt
```

I didn't suggest to remove the command: `kubectl create namespace "${KF_PROJECT}"`, but i am wondering if setting the current namespace is necessary.

**Comment by edi-bice-by** [comment]
I did run that command just prior to your reply. 

Actually grepped the whole repo and did not find it so I assumed it had not ran.

edibice@MD1-1029014MBP gcp-blueprints % grep 'set-context' -r *
kubeflow/hack/create_context.sh:kubectl config set-context --current --namespace=${NAMESPACE}
management/hack/create_context.sh:kubectl config set-context --current --namespace=cnrm-system
packages/management/hack/create_context.sh:kubectl config set-context --current --namespace=cnrm-system
tests/management/Makefile:	kubectl config set-context --current --namespace $(MANAGED_PROJECT)

After running that command it changed the namespace from cnrm-system to saas-ml-dev

The saas-ml-dev namespace though does not show when running your command

edibice@MD1-1029014MBP management % kubectl get namespace --context=kubeflow13-mgmt
NAME                              STATUS   AGE
cnrm-system                       Active   20h
configconnector-operator-system   Active   20h
default                           Active   20h
kube-node-lease                   Active   20h
kube-public                       Active   20h
kube-system                       Active   20h

**Comment by zijianjoy** [comment]
What you have explained confirms that you should run the following two commands from https://www.kubeflow.org/docs/distributions/gke/deploy/deploy-cli/#configure-kubeflow:

```
kubectl config use-context "${MGMTCTXT}"
kubectl create namespace "${KF_PROJECT}"
```

As long as you have done that, `kubectl get namespace --context=kubeflow13-mgmt` should show the namespace with "${KF_PROJECT}" name.

**Comment by zijianjoy** [comment]
After this, `make apply` should be successful for you.

**Comment by zijianjoy** [comment]
Feel free to reopen if you still face this issue.
