### ISSUE TITLE
Bad path spec in asm package while applying kubeflow blueprint 

### ISSUE THREAD

**Issue by edi-bice-by** [kubeflow/gcp-blueprints#260]
Went through after applying this change manually (since asm Makefile apply downloads fresh undoing change)
`diff --git a/kubeflow/common/asm/Makefile b/kubeflow/common/asm/Makefile
index 07a7dbf..de56987 100644
--- a/kubeflow/common/asm/Makefile
+++ b/kubeflow/common/asm/Makefile
@@ -39,8 +39,7 @@ install-asm: downalod-install-asm-script download-asm-package
        --mode install \
        --enable_all \
        --custom_overlay ./asm/istio/options/iap-operator.yaml \
\-       --custom_overlay ./options/ingressgateway-iap.yaml 
\-
\+       --custom_overlay ./asm/options/ingressgateway-iap.yaml 
 
 .PHONY: apply
 apply: install-asm`

**Comment by edi-bice-by** [comment]
Actually, install_asm via above failed at a later stage

install_asm: Configuring kpt package...
asm/
set 22 field(s) of setter "gcloud.container.cluster" to value "kf13"
asm/
set 40 field(s) of setter "gcloud.core.project" to value "saas-ml-dev"
asm/
set 2 field(s) of setter "gcloud.project.projectNumber" to value "285202620403"
asm/
set 6 field(s) of setter "gcloud.project.environProjectNumber" to value "285202620403"
asm/
set 21 field(s) of setter "gcloud.compute.location" to value "us-central1-a"
asm/
set 2 field(s) of setter "gcloud.compute.network" to value "saas-ml-dev-default"
asm/
set 6 field(s) of setter "anthos.servicemesh.rev" to value "asm-192-1"
asm/
set 2 field(s) of setter "anthos.servicemesh.tag" to value "1.9.2-asm.1"
csplit: *}: bad repetition count
csplit: ./options/ingressgateway-iap.yaml: No such file or directory
install_asm: Installing ASM control plane...
install_asm: [WARNING]: Failed, retrying...(1 of 5)
install_asm: [WARNING]: Failed, retrying...(2 of 5)
install_asm: [WARNING]: Failed, retrying...(3 of 5)
install_asm: [WARNING]: Failed, retrying...(4 of 5)
install_asm: [WARNING]: Failed, retrying...(5 of 5)

And ultimately was able to get it to complete ASM installation by specifying the faulty path absolutely

edibice@MD1-1029014MBP asm % ./install_asm \
        --project_id saas-ml-dev \
        --cluster_name kf13 \
        --cluster_location us-central1-a \
        --mode install \
        --enable_all \
        --custom_overlay ./asm/istio/options/iap-operator.yaml \
        --custom_overlay /Users/edibice/gcp-blueprints/kubeflow/common/asm/options/ingressgateway-iap.yaml

**Comment by zijianjoy** [comment]
Thank you @edi-bice-by , unfortunately ASM doesn't work well with macOS, because it comes with old version of bash. See https://cloud.google.com/service-mesh/docs/scripted-install/asm-onboarding#installing_required_tools.

This issue is one of many which will cause trouble when installing on MacOS. We recommend using Linux (local VM or on GCE instance) or Cloud Shell.

**Comment by Shaked** [comment]
@edi-bice-by @zijianjoy this issue can be fixed by replacing line 1304 in `install_asm`: 

Replace 
```
if [[ "$(csplit -f "overlay-${BASE_NAME}" "${yaml_file}" '/^---$/' '{*}' | wc -l)" -eq 1 ]]; then
```

With
```
if [[ "$(csplit -f "overlay-${BASE_NAME}" "${yaml_file}" '/^---$/' '{9999999}' | wc -l)" -eq 1 ]]; then
```

Following https://stackoverflow.com/questions/4323703/looking-for-correct-regular-expression-for-csplit, one of the comments state that the problem is not only the version number of bash, but rather the engine it is based on: 

> @slhck {*} is a convenient GNU extensions. Other csplit implementations require an explicit repetition count. Sometimes you can get away with a very large number ({999999999}), other times you need a first pass with grep. – Gilles 'SO- stop being evil' Jul 2 '13 at 18:25

This fixes the errors:

> csplit: *}: bad repetition count
csplit: ./options/ingressgateway-iap.yaml: No such file or directory
install_asm: Installing ASM control plane...
install_asm: [WARNING]: Failed, retrying...(1 of 5)
install_asm: [WARNING]: Failed, retrying...(2 of 5)
install_asm: [WARNING]: Failed, retrying...(3 of 5)
install_asm: [WARNING]: Failed, retrying...(4 of 5)
install_asm: [WARNING]: Failed, retrying...(5 of 5)
make[1]: *** [install-asm] Error 1
make: *** [apply] Error 1

and end up with:

> set 4 field(s) of setter "anthos.servicemesh.tag" to value "1.9.3-asm.2"
csplit: ^---$: no match
csplit: ./options/ingressgateway-iap.yaml: No such file or directory
install_asm: Installing ASM control plane...
install_asm: ...done!
install_asm: Installing ASM CanonicalService controller in asm-system namespace...
namespace/asm-system created
customresourcedefinition.apiextensions.k8s.io/canonicalservices.anthos.cloud.google.com created
...

Having said that, notice that `csplit: ./options/ingressgateway-iap.yaml: No such file or directory` still happens. Not sure why because the file is there

**Comment by edi-bice-by** [comment]
@Shaked tried that and got the same results as you. Will try upgrading bash next, thanks.

**Comment by edi-bice-by** [comment]
Upgraded bash using the instructions in the link @Shaked provided and still getting the error 

install_asm: Configuring kpt package...
asm/
set 22 field(s) of setter "gcloud.container.cluster" to value "kubeflow"
asm/
set 40 field(s) of setter "gcloud.core.project" to value "saas-ml-dev"
asm/
set 2 field(s) of setter "gcloud.project.projectNumber" to value "285202620403"
asm/
set 6 field(s) of setter "gcloud.project.environProjectNumber" to value "285202620403"
asm/
set 21 field(s) of setter "gcloud.compute.location" to value "us-central1-a"
asm/
set 2 field(s) of setter "gcloud.compute.network" to value "saas-ml-dev-default"
asm/
set 6 field(s) of setter "anthos.servicemesh.rev" to value "asm-193-2"
asm/
set 4 field(s) of setter "anthos.servicemesh.tag" to value "1.9.3-asm.2"
csplit: *}: bad repetition count
csplit: ./options/ingressgateway-iap.yaml: No such file or directory
install_asm: Installing ASM control plane...
install_asm: [WARNING]: Failed, retrying...(1 of 5)
install_asm: [WARNING]: Failed, retrying...(2 of 5)
install_asm: [WARNING]: Failed, retrying...(3 of 5)
install_asm: [WARNING]: Failed, retrying...(4 of 5)
install_asm: [WARNING]: Failed, retrying...(5 of 5)
make[1]: *** [install-asm] Error 1
make: *** [apply] Error 1
MD1-1029014MBP:kubeflow edibice$ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by edi-bice-by** [comment]
Installed asm manually as I described a few comments back but again despite the new bash it runs in csplit errors elsewhere - not sure what the effect will be but I guess I'll move on for now

asm/
set 4 field(s) of setter "anthos.servicemesh.tag" to value "1.9.3-asm.2"
csplit: *}: bad repetition count
csplit: *}: bad repetition count
install_asm: Installing ASM control plane...
