### ISSUE TITLE
deploy management cluster without docker

### ISSUE THREAD

**Issue by jackychow** [kubeflow/gcp-blueprints#338]
I'm following this kubeflow guide: https://www.kubeflow.org/docs/distributions/gke/deploy/management-setup/
trying to deploy a management cluster to GCP. It's stated that there's a dependency on docker and I also hit the error that docker is required while executing kpt-set.sh.

As docker has changed their terms and requires a paid subscription, I cannot use that for my company.
Is there a way to deploy kubeflow to GCP without using docker?

**Comment by zijianjoy** [comment]
@jackychow If you are deploying Kubeflow using your own account, I think you will still be able to run docker CLI without payment. But if you want to call the Kubeflow deployment with paid subscription, then you can find out the docker dependency and replace them with local yq command `YQ=yq` in https://github.com/kubeflow/gcp-blueprints/search?q=docker. It is mainly because we have been using docker for `yq` v4. If you install yq yourself, then you can just call the yq locally without docker: https://github.com/mikefarah/yq#install. 

The reason we use docker is that we can pin the yq version in order to avoid potential breaking changes with new release. But it might not happen as frequent.
